### ISSUE TITLE
[FEATURE] 프로젝트 세팅

### ISSUE THREAD

**Issue by hoyahozz** [wanted-preonboarding-hoyahozz/android-wanted-CustomKeyboardApp#1]
## 🤔 목적

> 베이스 작업 진행

## 📝 TO-DO

- [x] Presentation 레이어 모듈 구현
- [x] Data 레이어 모듈 구현
- [x] Domain 레이어 모듈 구현
