### ISSUE TITLE
[FEATURE] 키보드 클립보드 복사 기능 추가

### ISSUE THREAD

**Issue by sujin-kk** [wanted-preonboarding-hoyahozz/android-wanted-CustomKeyboardApp#3]
## 🤔 목적

> 키보드 툴바 영역에 클립보드 메뉴를 추가하고 복사한 문장 local에 저장 및 띄우는 기능입니다.

## 📝 TO-DO

- [x] 키보드 입력 문장 룸에 저장
- [x] 클립보드 영역에 룸에 저장된 단어들 띄우기
- [x] 해당 단어 아이템 누르면 edit text에 자동 입력
- [x] 각 단어 아이템의 x 눌러서 룸에서 삭제

**Comment by sujin-kk** [comment]
resolve
