### ISSUE TITLE
[FEATURE] 키보드 단축키 기능 추가

### ISSUE THREAD

**Issue by INAH-PAK** [wanted-preonboarding-hoyahozz/android-wanted-CustomKeyboardApp#4]
## 🤔 목적

> 단축키(스페이스바 왼쪽) 구현

## 📝 TO-DO

> - #### 단축키 길게 클릭시

- [x]  등록된 단축어를 **입력**할 수 있고, **설정**할 수 있는 UI를 키보드 위에 띄우기
- [ ]   **설정** 선택시 단축어를 등록, 삭제할 수 있는 Dialog 띄우기
- [ ]   단축어 설정 Dialog에서 사용자의 단축어 저장, 삭제시 RoomDB에 단축어 저장, 삭제
- [x]   단축키를 길게 누른 후, 손을 뗐을 때 단축키에 해당 단축어 **고정** + **입력**

> - #### 단축키 짧게 클릭시

- [x]  현재 단축키에 표시된( 고정된 ) 문자열이 입력됨
